codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: '85...100'
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        only_pulls: true
    changes: false

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

flags:
  unittests:
    paths:
      - src
    carryforward: true

ignore:
  - '**/*.test.ts'
  - '**/*.bench.ts'
  - '**/*.d.ts'
  - 'dist/**/*'
  - 'coverage/**/*'
  - '**/*.config.*'
